version: "3.9"

services:
  api01: &api
    image: matheusvict/rinha-de-backend-q1-quarkus:latest
    hostname: api01
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db:5432/rinha
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=40
      - QUARKUS_DATASOURCE_REACTIVE_EVENT_LOOP_SIZE=4
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    #deploy:
     # resources:
      #  limits:
       #   cpus: '0.35'
        #  memory: '120MB'


  api02:
    <<: *api
    hostname: api02
    depends_on:
      - db
      - api01
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://db:5432/rinha
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE=40
      - QUARKUS_DATASOURCE_REACTIVE_EVENT_LOOP_SIZE=4
    ports:
      - "8082:8080"


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50MB"


  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5431:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./script.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    command: [ "postgres", "-c", "logging_collector=false", "-c", "max_connections=450", "-c" , "config_file=/etc/postgresql/postgresql.conf" ]
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '500MB'
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U admin -d rinha -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1