name: Build Docker Native Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          distribution: 'adopt'

      - name: Build rinha API Container Image
        run: mvn package clean package -DskipTests -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus-reactive:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus-reactive:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus-reactive:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rinha-de-backend-q1-quarkus-reactive:latest
